### ISSUE TITLE
数据集与源代码不匹配的问题

### ISSUE THREAD

**Issue by Yuluer** [BeechburgPieStar/FS-SEI#1]
作者您好，您的源代码中输入维度是6000的，而提供的数据集是4800，请问能够提供6000的数据集吗，或者是4800的源代码，感谢！

**Comment by BeechburgPieStar** [comment]
您好！很抱歉代码和权重忘记更新了，目前github和百度网盘已经更新。此外，实验结果以github更新的为准（这个是基于移除了ICAO码的4800数据），论文里面6000那个数据有些问题，我们近期正在着手撰写comment修正论文的结果。如果还有问题请与我联系（微信15851811703）。

**Comment by BeechburgPieStar** [comment]
> 



> 作者您好，您的源代码中输入维度是6000的，而提供的数据集是4800，请问能够提供6000的数据集吗，或者是4800的源代码，感谢！

您好！很抱歉代码和权重忘记更新了，目前github和百度网盘已经更新。此外，实验结果以github更新的为准（这个是基于移除了ICAO码的4800数据），论文里面6000那个数据有些问题，我们近期正在着手撰写comment修正论文的结果。如果还有问题请与我联系（微信15851811703）。

**Comment by Yuluer** [comment]
非常感谢您的回复！遇到问题我会联系您的！
