### ISSUE TITLE
数据集类别问题

### ISSUE THREAD

**Issue by DylanCZW** [BeechburgPieStar/FS-SEI#2]
楼主您好，我想问一下给的数据集中90class和10class分别是不同的类别吗，还是说10class对应的是90class中的0-9类别

**Comment by BeechburgPieStar** [comment]
90类和10类不是一样的类别，这个数据集原本是120类，我分割为一个90类的训练集、30类的小样本训练与测试集，其中10类、20类都是从30类中提取出来的

**Comment by DylanCZW** [comment]
非常感谢🙏
